Repository antoniokot/culympics-paris, pull requests merged in 2024-06, with the labels that each got.

#35 Resolve atividade4
  README.md
  atividades/atividade_4/imagens/arquitetura.png
Labels: AtividadeA4

#41 Fix/resolve code smells
  culympics-paris-front/package.json
  culympics-paris-front/src/components/Header/Header.test.tsx
  culympics-paris-front/src/components/Header/styles.ts
  culympics-paris-front/src/components/RestaurantCard/index.tsx
  culympics-paris-front/src/components/RestaurantCard/styles.ts
  culympics-paris-front/src/pages/Explore/Explore.test.tsx
  culympics-paris-front/src/pages/Home/Home.test.tsx
  culympics-paris-front/src/pages/Home/styles.ts
  culympics-paris-front/src/pages/Search/styles.ts
  culympics-paris-front/tsconfig.json
  culympics-paris-front/vite.config.ts
Labels: frontend, AtividadeA4

#42 chore: improve readme.md
  README.md
Labels: AtividadeA4

#39 FIX: code smells
  build/local/database/Dockerfile
Labels: AtividadeA4

#47 feat: Add backend unit-tests for api layer
  culympics-paris-api/Makefile
  culympics-paris-api/go.mod
  culympics-paris-api/go.sum
  culympics-paris-api/internal/api/mocks/RestaurantService.go
  culympics-paris-api/internal/api/restaurant_test.go
  culympics-paris-api/internal/service/mocks/RestaurantDao.go
Labels: AtividadeA5

#46 feat: create unit tests for atividade5
  culympics-paris-front/src/components/Header/Header.test.tsx
  culympics-paris-front/src/components/RestaurantCard/RestaurantCard.test.tsx
Labels: AtividadeA5
